name: iOS • Build unsigned .ipa (Capacitor + Vite)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-ios:
    runs-on: macos-latest
    env:
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm install --no-audit --no-fund

      - name: Build web (Vite)
        run: npm run build

      - name: Ensure Capacitor iOS platform
        run: |
          npx cap doctor || true
          if [ ! -d ios ]; then
            echo "Adding iOS platform (non-interactive)..."
            yes | npx cap add ios
          else
            echo "iOS platform already present, skipping add."
          fi

      - name: Sync web assets to iOS
        run: npx cap copy ios

      - name: CocoaPods install
        run: |
          sudo gem install cocoapods -N || true
          cd ios/App
          pod repo update || true
          pod install

      - name: Xcode archive (unsigned)
        run: |
          set -e
          cd ios
          WORKSPACE="App/App.xcworkspace"
          SCHEME="App"
          ARCHIVE_PATH="$PWD/build/GiannicorpAdmin.xcarchive"
          xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -configuration Release -destination 'generic/platform=iOS' -archivePath "$ARCHIVE_PATH" CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO archive

      - name: Package .ipa
        run: |
          set -e
          APP_PATH=$(find ios/build/GiannicorpAdmin.xcarchive/Products/Applications -name "*.app" -maxdepth 1 -print -quit)
          if [ -z "$APP_PATH" ]; then
            echo "❌ .app not found in archive"; exit 1; fi
          mkdir -p Payload
          cp -R "$APP_PATH" Payload/
          /usr/bin/zip -qry GiannicorpAdmin-unsigned.ipa Payload
          rm -rf Payload

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: GiannicorpAdmin-unsigned-ipa
          path: GiannicorpAdmin-unsigned.ipa